name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
      is_prerelease:
        description: 'Is prerelease Version'
        type: boolean
        required: true

env:
  LOL2GLTF_RID: "win10-x64"
  LOL2GLTF_CLI_RID: "win-x64"
  
  LOL2GLTF_PROJECT: "lol2gltf"
  LOL2GLTF_CLI_PROJECT: "lol2gltf.CLI"
  
  LOL2GLTF_OUTPUT: "lol2gltf_win10-x64"
  LOL2GLTF_CLI_OUTPUT: "lol2gltf.CLI_win-x64"
  
  BUILD_CONFIG: "Release"

jobs:
  publish-lol2gltf:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish ${{ env.LOL2GLTF_PROJECT }} --no-restore -c ${{ env.BUILD_CONFIG }} -o ${{ env.LOL2GLTF_OUTPUT }} -r ${{ env.LOL2GLTF_RID }} -p:PublishSingleFile=true --self-contained true
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.LOL2GLTF_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_RID }}"
          path: "${{ env.LOL2GLTF_OUTPUT }}"
  
  publish-lol2gltf-cli:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish ${{ env.LOL2GLTF_CLI_PROJECT }} --no-restore -c ${{ env.BUILD_CONFIG }} -o ${{ env.LOL2GLTF_CLI_OUTPUT }} -r ${{ env.LOL2GLTF_CLI_RID }} -p:PublishSingleFile=true --self-contained true
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.LOL2GLTF_CLI_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_CLI_RID }}"
          path: "${{ env.LOL2GLTF_CLI_OUTPUT }}"
  release:
    needs: [publish-lol2gltf, publish-lol2gltf-cli]
  
    runs-on: windows-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Download lol2gltf Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: "${{ env.LOL2GLTF_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_RID }}"
          path: "${{ env.LOL2GLTF_PROJECT }}_publish"
          
      - name: Download lol2gltf.CLI Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: "${{ env.LOL2GLTF_CLI_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_CLI_RID }}"
          path: "${{ env.LOL2GLTF_CLI_PROJECT }}_publish"
      
      - name: Package lol2gltf
        run: 7z a "${{ env.LOL2GLTF_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_RID }}.zip" "./${{ env.LOL2GLTF_PROJECT }}_publish/*"
      
      - name: Package lol2gltf.CLI
        run: 7z a "${{ env.LOL2GLTF_CLI_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_CLI_RID }}.zip" "./${{ env.LOL2GLTF_CLI_PROJECT }}_publish/*"
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.is_prerelease }}
          append_body: true
          files: |
            "${{ env.LOL2GLTF_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_RID }}.zip"
            "${{ env.LOL2GLTF_CLI_PROJECT }}_${{ github.event.inputs.version }}_${{ env.LOL2GLTF_CLI_RID }}.zip"

